### ISSUE TITLE
You gonna speak at JSConf.Asia this year? :)

### ISSUE THREAD

**Issue by serrynaimo** [cheeaun/ama#1]

**Comment by notthetup** [comment]
:+1:

**Comment by sayanee** [comment]
:+1:

**Comment by ksaitor** [comment]
:+1:

**Comment by kahwee** [comment]
:+1: I love the thumbs up activism.

**Comment by prathamesh-sonpatki** [comment]
:+1:

**Comment by cheeaun** [comment]
Got to say this is a good question, and a pretty frequent question that people ask me these days. But I couldn't give a straight, simple answer. It's because there's a story behind it which no one will take the time to hear me out.

When I was in university, I've always dreamed of speaking in a conference, like some of my web super heroes who I admired. But I'm not good at speaking, so I decided to _train_ myself. My first public talk was in BarCamp KL in [2008](http://cheeaun.com/blog/2008/09/meaningful-three-years) which @kamal manage to persuade me to give a talk. It was very scary but somehow feels good. People were actually interested to listen to my talk and that makes me feel appreciated.

Since then, I gave [a bunch of talks in KL and later in Singapore](http://cheeaun.com/blog/2010/01/goodbye-2009-hello-2010) (around 2009). I sort of tried different kinds of talks; talk with slides, talk with demo, talk **without** slides, etc. Among all the talks I gave, the one that I had the **best experience** is [Story of A Thousand Birds](http://www.slideshare.net/cheeaun/story-of-a-thousand-birds) in GeekCamp KL on 30th May 2009. The audience was very engaged and as I talk, I could feel people there were very focused on what I'm trying to share at that unforgettable moment. I remember @sausheong @jasonong were there too.

Ever since then, I've been trying to "relive" the moment but got disappointed over and over again. And finally I stopped giving talks. Perhaps I'm too picky on things or being too perfectionist.

If one day, I were to give a talk again, I would request for these:
- Ideally one hour of speaking time, no Q&A, extend time if I go on further (I also have a habit of short-cutting my talk, taking lesser time, if I spot people not interested to listen to me. I know, good speakers adjust the timing and speaking style based on the audience, in real-time).
- A working microphone. Really hate it when I have to shout.

That's pretty much it.

So back to the question, my short answer is _yes_, but I don't have a concrete topic yet. I have few things in mind but hopefully can come up with one final topic just in time.

**Comment by ksaitor** [comment]
- A working microphone provisioned shall be, under my command :wink:
- Sir @serrynaimo, please confirm one hour of speaking time.

**Comment by jasonong** [comment]
@cheeaun I remembered your talk at that fateful Geekcamp. It was my favorite at that event and contributed heavily towards the first GeekcampSG. :+1:

**Comment by notthetup** [comment]
I remember your talk at the old HackerspaceSG. I think it was at some Hack&Tell. You talked about some Safari issue of doing overflows and scrollbars within another scrolling div. That was a a good one.

**Comment by sayanee** [comment]
I remember your hack & tell and also another one at one of the first front end meetups. I loved them!

If anything, there are so many of us who loves and misses your talk. No pressure, but your sharing will really encourage many young and old in the industry. 

See you speaking at a talk soon 💜💛💚💙💖

**Comment by sausheong** [comment]
I liked the Story of a Thousand Birds. Glad you're picking up speaking again. Talk about your KopiJS experiences? Do something _not_ mainstream.

**Comment by serrynaimo** [comment]
In the end you do this for yourself and because you like sharing, teaching and giving people a good time. But if you need more reasons, do it because we need more people from our local eco-system to take the plunge and inspire others to do the same.
I can make sure you get the audience you deserve that can truly appreciate the ingenuity and hard work that was put into your work. The one hour time-slot shouldn't be a problem and if I believe @ksaitor the microphone will be working, too, without feedback and at just the right volume. I for myself would be delighted and am looking forward to an email from you any day! See you at the next KopiJS! :)

**Comment by cheeaun** [comment]
Well, this question finally have an answer. Not 2015, but 2016 instead.
- https://2016.jsconf.asia/
- https://twitter.com/jsconfasia/status/769055813457543171
- https://www.facebook.com/JSConfAsia/posts/909584412478976

Closing 🎉
