### ISSUE TITLE
What's your favorite part about Singapore?

### ISSUE THREAD

**Issue by sindresorhus** [cheeaun/ama#10]

**Comment by cheeaun** [comment]
Well simply these:
- Great transportation system (buses, trains, taxis).
- Cleanliness. Everywhere you go in Singapore, it's always clean.
- Singapore serves as a good hub or starting point to travel to other places. Changi Airport is just awesome.

**Comment by rstacruz** [comment]
followup: what do you hate/dislike about Singapore?

**Comment by cheeaun** [comment]
Well... the cons would be:
- Hot weather, sometimes. But glad to know that summer in other countries are actually hotter than Singapore's warmth.
- Even though taxis are very accessible, some drivers always ask you which road/path you _prefer_. It's kind of odd though understandable that some local people are quite picky on which road/path to take.
- Some ISPs like SingTel runs a _transparent_ proxy which does some caching and messes up some pages. I had issues before with `CORS` headers being stripped off from responses. Turns out that the easiest solution is just serve everything in HTTPS.
- Expensive house/room rentals. Expensive cars. Sometimes expensive food though if you're local enough, there are some very cheap food.
