### ISSUE TITLE
What camera do you use?

### ISSUE THREAD

**Issue by laktek** [cheeaun/ama#15]
I know you do lot of travel photography. Are those all captured from an iPhone? If so, are you using any camera apps?

Also, please share some of your favorite shots.

**Comment by cheeaun** [comment]
Most (if not all) of my photos are taken from my iPhone. I'm not really into the the more advanced photography category, using all those super-expensive cameras. I used to try a bunch of photography apps and Instagram filters were one of them. But [ever since I got iPhone 5S](https://twitter.com/cheeaun/status/409584567096332289), I've slowly stopped using any filters because I think those are invented to _compensate_ the weakness of the camera in previous iPhone generations.

I'm not saying that filters are bad. Filters are actually nice to use when you feel artistic. It's like seeing the world in a different way. For me, I just want to see the world as it is, and I want to share that to other people. The more the camera lenses matches what I see from my eyes, the better it is. There are some times when iPhone camera doesn't do a good job, especially night shots, so that's when I use Instagram's fine-tuning tools (not the filters) to adjust saturation, sharpness, highlight, etc. Sometimes I try to adjust them to look like real-world. Sometimes I tune it to amplify certain features which I think is important in the photo.

Some of my favorite shots are on my [Instagram](https://instagram.com/cheeaun/) (Follow me please). Here are a few of my favorite shots with some story behind them:

[![](https://farm6.staticflickr.com/5526/14008325487_03119782d4_h.jpg)](https://www.flickr.com/photos/cheeaun/14008325487/in/album-72157644277519688/)
This is a rather surprising shot for me. I was walking on this **Pier 7** in SF. Feeling tired after walking all the way from Fisherman's Wharf, I look towards the sea and there's like nothing much (I took too many "sea shots" that time). Bay Bridge on the right, and way further left is the Golden Gate Bridge. By the time I turn back, I saw this view. The sun rays were bright so it's pretty hard to focus with the iPhone. The lamp posts are actually not lit but seems reflected from the sun light. The bird flying at the top right is a nice touch in my opinion.

[![](https://farm6.staticflickr.com/5111/14014950859_f0723d18ba_h.jpg)](https://www.flickr.com/photos/cheeaun/14014950859/in/album-72157644277519688/)
I like panorama shots, but it's always difficult to take really good ones. It's difficult when the exposure and light changes as you pan across a scenery, and some details are missing, for example the sun light in this photo. This is when I wish the phone camera is better as I want to highlight more details on the wooden house building in the middle. It looks **way better** in reality than this photo.

[![](https://farm8.staticflickr.com/7754/17354582231_1ac9fd7c92_h.jpg)](https://www.flickr.com/photos/cheeaun/17354582231/in/album-72157651925636988/)
I love going up hills and take photos. The hiking process gives you a sense of achievement once you reach the top and take photos of the amazing view. There are also similar experiences if you go for Sky Tower in Sydney, TV Tower in Berlin or even Eiffel Tower in Paris, but the effort it takes to go up **makes a difference**. This is Mount Eden in Auckland, New Zealand. It was quite a challenging hike for me because it was also raining or drizzling on and off while I'm going up the steep trails. When I reach the top, I totally didn't expect the crater at all. And if you zoom in the photo, there's an umbrella and some stone decorations in the middle of the crater. I don't know how they got there but seems kinda hilarious to me.

There are probably few more photos that I like but let's leave it for next time when I revisit this issue :smile:

**Comment by laktek** [comment]
bigger thumbnails when you revisit the issue?

**Comment by cheeaun** [comment]
Updated the photos to be bigger. Realised that the thumbnails in a table shrank really small on a mobile device, so not really a good idea.

**Comment by valentine** [comment]
Great answer! Love the stories behind the photos! :+1:

**Comment by sssionggg** [comment]
those pictures are awesome!

**Comment by redhae** [comment]
wow, nice!
