### ISSUE TITLE
Whats your favourite/goto front-end stack/tools/libs?

### ISSUE THREAD

**Issue by alyssaq** [cheeaun/ama#4]
And for testing.

**Comment by sayanee** [comment]
:+1:

**Comment by cheeaun** [comment]
Since front-end stuff changes _all the time_, my favorite/goto front-end stack/tools/libs as of 9th July 2015 are:
- [React](http://facebook.github.io/react/) for writing complex frontend UIs
- [Babel](https://babeljs.io/) for ES6/7/\* magic
- _Vanilla_ [npm scripts](https://docs.npmjs.com/misc/scripts) instead of Grunt/Gulp/etc
- _Any_ browser debugger/inspector
- _Still_ [mocha](https://github.com/mochajs/mocha) for testing (sometimes), also probably because I like to drink mocha
- [Can I use...](caniuse.com/) for references on what I can use...
- [WebPageTest](http://www.webpagetest.org/) for performance testing
- [JSBin](http://jsbin.com/) when I need to demo or try something
- [Coolors](http://coolors.co/) for super-lazy color choosing
- [SVGOMG](https://jakearchibald.github.io/svgomg/) for some SVG _massaging_.
- [css/edge](http://meyerweb.com/eric/css/edge/) - My all-time favorite. The site that inspires me to learn CSS.
- [MooTools](http://mootools.net/) - I don't use it anymore but it's the first JS library I learnt which _encourages_ me to learn (raw) JavaScript, instead of just stuck to a single library's vocabulary.
